server.port=8080
server.servlet.context-path=/
spring.application.name=app-gestion-trabajo-colaborativo

# Configuración de Spring
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Logging
logging.level.root=INFO
logging.level.pds.app_gestion=DEBUG
